[package]
name = "Student_marks"
version = "0.1.0"
authors = ["vaibhav Thombare <vaibhav.thombare@joshsoftware.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
